apiVersion: v2
name: operator
icon: https://kadalu.io/static/css/logo.png
description: kadalu.io Storage Operator and CSI for k8s (with glusterfs)
type: application
# Value of 'version' will be replaced with correct version on part of release
version: 0.0.0-0
