name: On ARM branch push

on:
  push:
    paths-ignore:
      - 'doc/**'
      - '**.md'
      - 'extras/**'
      - 'helm/**'
      - 'tests/**'
    branches:
      - arm
# Add tags later (for pushing release)


jobs:
  arm-tag-push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out Code
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Python (for cli-build)
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Get the CLI build (kubectl-kadalu)
        run: |
          python -m pip install -r requirements/ci_merge-requirements.txt
          KADALU_VERSION=devel make cli-build
      - name: Copy all requirements files to root of the repo for building images
        run: |
          cp -r requirements/* .
      -
        name: Build Builder Image
        uses: docker/build-push-action@v2
        timeout-minutes: 200
        with:
          context: .
          file: extras/Dockerfile.builder
          platforms: linux/arm64,linux/arm/v7
          push: false
          tags: |
            docker.io/kadalu/builder:latest
            docker.io/kadalu/builder:arm
          build-args: |
            version==${{ github.sha }}
            builddate=`date +%Y-%m-%d-%H:%M`
          secrets: |
            KADALU_VERSION=latest
      -
        name: Build CSI Image and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: csi/Dockerfile
          platforms: linux/arm64,linux/arm/v7
          target: prod
          push: true
          tags: |
            docker.io/kadalu/kadalu-csi:${{ github.sha }}
            docker.io/kadalu/kadalu-csi:arm
          build-args: |
            version==${{ github.sha }}
            builddate=`date +%Y-%m-%d-%H:%M`
          secrets: |
            KADALU_VERSION=${{ github.sha }}
      -
        name: Build Operator Image and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: operator/Dockerfile
          platforms: linux/arm64,linux/arm/v7
          target: prod
          push: true
          tags: |
            docker.io/kadalu/kadalu-operator:${{ github.sha }}
            docker.io/kadalu/kadalu-operator:arm
          build-args: |
            version==${{ github.sha }}
            builddate=`date +%Y-%m-%d-%H:%M`
          secrets: |
            KADALU_VERSION=${{ github.sha }}
      -
        name: Build Storage Server Image and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: server/Dockerfile
          platforms: linux/arm64,linux/arm/v7
          target: prod
          push: true
          tags: |
            docker.io/kadalu/kadalu-server:${{ github.sha }}
            docker.io/kadalu/kadalu-server:arm
          build-args: |
            version==${{ github.sha }}
            builddate=`date +%Y-%m-%d-%H:%M`
          secrets: |
            KADALU_VERSION=${{ github.sha }}
